[theme]

# The preset Streamlit theme that your custom theme inherits from.
# One of "light" or "dark".
base = "light"

# Used to style primary interface elements. It's the color displayed most
# frequently across your app's widgets (slider, checkbox, buttons)
primaryColor = "#6FB3B8" 

# Background color for the main container.
backgroundColor = "#F6F6F2"

# Used as the background for most widgets (sidebar, text input etc.)
secondaryBackgroundColor =  "#ffffff"

# Font color for the page.
textColor = "#3B6467"

# Font family for the page. (One of "serif", "sans serif" or "mono")
font = "sans serif"

[client]
showSidebarNavigation = false